steps:
- name: 'gcr.io/cloud-builders/npm'
  args: ['install']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['config', 'set', 'project', 'muv-retail-prod']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', 'retail-api-prod.yaml']
timeout: '1600s'